config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "dashboard#index"

  # Resources for services
  resources :services
  resources :contacts, only: [:index]
  resources :about, only: [:index]

  resources :bookings do
    collection do
      get :unavailable_times
    end
  end

end

app/views/layouts/_footer.html.erb
<div class="bg-gradient-to-r from-black to-gray-900 text-gray-200 min-h-[20rem] sm:min-h-[25rem] md:h-80 lg:h-96 flex items-center justify-center text-center px-4 py-12 sm:py-16 md:py-20">
  <div>
    <p class="text-base sm:text-lg md:text-xl poppins-light">Like what you see?</p>
    <p class="text-2xl sm:text-3xl md:text-4xl poppins-extrabold my-2 sm:my-3 md:my-4">Book your wash!</p>
    <p class="text-lg sm:text-xl md:text-2xl poppins-light">Limco Carwash Brisbane Northside, your local choice.</p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="bg-white sticky top-0 z-50 shadow-md" data-controller="navbar">

  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="flex-shrink-0 flex items-center">
        <%= link_to root_path do %>
          <%= image_tag "logonobg.png", alt: "Logo", class: "h-16 w-44 rounded-lg" %>
        <% end %>
      </div>
      <div class="hidden sm:block sm:ml-6">
        <div class="flex space-x-4">
          <%= link_to "Services", services_path, class: "hover:bg-gray-100 block px-3 py-2 rounded-md text-base poppins-regular cursor-pointer", style: 'color:#16006C;' %>
          <%= link_to "Contact", contacts_path, class: " hover:bg-gray-100 block px-3 py-2 rounded-md text-base poppins-regular cursor-pointer", style: 'color:#16006C;' %>
          <% if current_user && current_user.email == 'admin@gmail.com' %>
            <%= link_to 'Bookings', bookings_path, class: "hover:bg-gray-100 block px-3 py-2 rounded-md text-base poppins-regular cursor-pointer", style: 'color:#16006C;' %>
          <% end %>
          <% if user_signed_in? %>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "hover:bg-gray-100  block px-3 py-2 rounded-md text-base poppins-regular cursor-pointer", style: 'color:#16006C;' %>
          <% else %>
            <%= link_to 'Login', new_user_session_path, class: "hover:bg-gray-100  block px-3 py-2 rounded-md text-base poppins-regular cursor-pointer", style: 'color:#16006C;' %>
          <% end %>
        </div>
      </div>
      <div class="sm:hidden">
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" data-action="click->navbar#toggleMenu" style="color: #16006C;">
          <!-- Icon when menu is closed -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" data-navbar-target="openIcon">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!-- Icon when menu is open -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" data-navbar-target="closeIcon">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu, toggle classes based on menu state -->
  <div class="sm:hidden hidden" data-navbar-target="menu">
    <div class="px-2 pt-2 pb-3 space-y-1">
          <%= link_to "Services", services_path, class: "flex justify-center hover:bg-gray-100  block px-3 py-2 rounded-md text-base poppins-regular cursor-pointer", style:"color: #16006C;" %>
          <%= link_to "Contact", contacts_path, class: "flex justify-center hover:bg-gray-100  block px-3 py-2 rounded-md text-base poppins-regular cursor-pointer", style:"color: #16006C;" %>
          <% if current_user && current_user.email == 'admin@gmail.com' %>
            <%= link_to 'Bookings', bookings_path, class: "flex justify-center hover:bg-gray-100  block px-3 py-2 rounded-md text-base poppins-regular cursor-pointer", style:"color: #16006C;" %>
          <% end %>
          <% if user_signed_in? %>
          <div class="flex justify-center hover:bg-gray-100">
              <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "block px-3 py-2 rounded-md text-base poppins-regular cursor-pointer", style:"color: #16006C;" %>
          </div>
          <% else %>
            <%= link_to 'Login', new_user_session_path, class: "flex justify-center hover:bg-gray-100  block px-3 py-2 rounded-md text-base poppins-regular cursor-pointer", style:"color: #16006C;" %>
          <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('favicon.png'), type: 'image/png' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <title>Limco Car Wash</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%#= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%# tailwind CDN below %>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <%= stylesheet_link_tag 'fonts', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <main>
      <%= yield %>
    </main>
        <% unless controller.controller_name == 'bookings' && action_name == 'index' %> <!-- Exclude footer on bookings#index -->
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>